name: location
description: use android and ios native API positing
version: 0.0.4
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"


dependencies:
  flutter:
    sdk: flutter
  location_platform_interface:
#    path: ../location_platform_interface
    git:
      url: https://github.com/chengbook/location_platform_interface.git
      ref: 0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.cheng.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
